# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7b67de9b7d1ebeb34f8af2db64c2e31b770f93e01bec901a9428c9bb7ac85609fd389185407622050da75c2cb788d7e9befac8515b2ae3100448f85085f00e9

test:
  secret_key_base: 4a17a69b84274cfc960ba1690406bf9fed7e592be502798d10dc22d2722e120c954f1b868009d14d3c78926766e80fe297356960cebd1d7fd35bf06a83250987

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
